# Generated by Django 4.2.5 on 2023-09-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkservice_app', '0003_alter_task_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='homeworkservice_app.subject'),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeworkservice_app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='school_class',
            field=models.ManyToManyField(null=True, to='homeworkservice_app.schoolclass'),
        ),
    ]
