# Generated by Django 4.2.5 on 2023-09-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkservice_app', '0007_teacher_available_school_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='available_school_classes',
        ),
    ]
