# Generated by Django 4.2.5 on 2023-09-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkservice_app', '0008_remove_teacher_available_school_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='available_school_classes',
            field=models.ManyToManyField(to='homeworkservice_app.schoolclass'),
        ),
    ]
